Context setting
wafflestudio20-5/team7-web pull request #10
Opened 2023-01-13 21:12 UTC by 2-0-is

타입 세팅과 로그인 context는 만들었는데 코드 양이 많아 리팩토링까지는 못했습니다..
일단 헤더만 로그인 context에 연결해두었습니다.

모든 페이지에서 타입을 정리하고 변수명 통일을 하면 시간이 너무 오래 걸릴 것 같아 지금 작업해야하는 각 포스트별 페이지, 포스트 작성, 임시 포스트, 로그인페이지(새로 만들어질 페이지)는 제외하고 타입 정리(변수명 통일, 분산된 타입 정의 합치기, login context 연결) 해두려고 합니다.
작업하시는 페이지는 provider, types 파일 참고하여 구현해주시면 좋을 것 같습니다..!

2023-01-13 21:55 UTC, Howon-Shin requested changes
작동 확인했습니다. 빠른 시일 내에 제가 만든 페이지에 대충 넣은 값들 interface로 다시 정의해서 types에 넣도록 하겠습니다.

2023-01-13 21:55 UTC, Howon-Shin commented on src/App.tsx
> +
```
function AppProvider({ children }: { children: React.ReactNode }) {
  retrun (
    <LoginProvider>
      <ModalProvider>{children}</ModalProvider>
    </LoginProvider>
  );
}
```
위 코드처럼 합쳐서 쓰는 게 깔끔할 것 같습니다.

2023-01-13 21:55 UTC, Howon-Shin commented on src/components/Header.tsx
> +                className={useLoginValue().isLogin ? cx('user') : cx('blind')}
`const { isLogin } = useLoginValue()`로 위에서 선언해서 받아오는 게 좋을 것 같아요.

2023-01-14 02:17 UTC, silky225 reviewed
확인했습니다. 제가 만든 페이지에 type을 반영하고, loginSetting의 함수들은 추후 형식이 확정되면 수정하도록 하겠습니다.

2023-01-14 06:56 UTC, Howon-Shin approved these changes

2023-01-14 07:12 UTC, merged